# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='index.ContentCategory', verbose_name='类别'),
        ),
    ]
